### ISSUE TITLE
Can't install new software due to privilege issue

### ISSUE THREAD

**Issue by vipnaik** [WASdev/ci.docker.websphere-traditional#104]
I was able to run container successfully using image ibmcom/websphere-traditional:8.5.5.12-install. Server is running.
Now I am inside container and want to install new softwares like unzip and wget using apt-get.
But while trying that I am getting below error:

_E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?_

**Comment by davidcurrie** [comment]
As the error suggests, you are not root. In general, you don't want to be installing software in a running container. If you want to add new packages, do so in a Dockerfile when you are building the image. You can then use the `USER` directive to switch to `root` and then back to the `WAS` user.

**Comment by vipnaik** [comment]
Hi @davidcurrie ,
Okay. I will try that.

**Comment by arthurdm** [comment]
any luck with that @vipnaik?

**Comment by arturdzm** [comment]
Closing, re-open if needed
