### ISSUE TITLE
WAS ND 8.5.5.5

### ISSUE THREAD

**Issue by bru2code** [WASdev/ci.docker.websphere-traditional#115]
HI, 

Is the below doc still valid if I want to create WAS ND 8.5.5.5 container image or better files availabel that I can use ? I can't find `cd ci.docker.websphere-traditional/network-deployment/install/` and install instructions seem to suggest other wise. 

https://developer.ibm.com/recipes/tutorials/how-to-configure-ibm-websphere-application-server-network-deployment-cell-topology-using-docker-containers/ 

Thanks, Bru

**Comment by arthurdm** [comment]
hi @bru2code - unfortunately no, we do not support running WAS traditional ND in containers.   The management plane that ND provides, in a container world, conflicts with orchestration frameworks such as Kubernetes.  

Have you looked at deploying WAS base containers, or Liberty containers in Kubernetes?

**Comment by arthurdm** [comment]
@bru2code - if you can downgrade to WAS base, please give our [new instructions](https://github.com/WASdev/ci.docker.websphere-traditional#docker-hub-image) a try.  Also, I would recommend checking out the work we're doing with [Liberty in kubernetes](https://www.ibm.com/blogs/bluemix/2018/10/certified-kubernetes-deployments-for-websphere-liberty/).   

If you really need to use WAS ND, I recommend looking into the [VM Quickstarter](https://www.ibm.com/blogs/bluemix/2018/10/migrate-your-websphere-app-to-vm-in-the-cloud/)
