### ISSUE TITLE
Unable to get wsadmin password from /tmp/PASSWORD

### ISSUE THREAD

**Issue by shareauto** [WASdev/ci.docker.websphere-traditional#118]
There is no password under the /tmp/PASSWORD, Please find the below command output for your reference.

[root@fsr3vlwaspoc1 ~]#‌ docker ps

CONTAINER ID    IMAGE                 COMMAND         CREATED       STATUS       PORTS                      NAMES

18321f1d8492    ibmcom/websphere-traditional:latest  "/work/start_serve..."  2 hours ago     Up About an hour  0.0.0.0:9043->9043/tcp, 0.0.0.0:9443->9443/tcp  test

[root@fsr3vlwaspoc1 ~]#‌ docker exec test cat /tmp/PASSWORD

cat: /tmp/PASSWORD: Is a directory

[root@fsr3vlwaspoc1 ~]#‌

**Comment by arthurdm** [comment]
hi @shareauto - how did you start the image?    also, did you do a `docker pull ibmcom/websphere-traditional` to get the latest image?

**Comment by shareauto** [comment]
Yes I did start the image, and I can able to get the WAS admin console but I cannot login as wsadmin because I dont know the password. Yes I did docker pull ibmcom/websphere-traditional to get latest image.

I used the following command to start the docker image

docker run --name test -h test -v $(pwd)/PASSWORD:/tmp/PASSWORD   -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:latest /bin/bash9043 -p 9443:9443 -d ibmcom/websphere-traditional:latest /bin/

**Comment by arturdzm** [comment]
This is due to your mount being somehow incorrect. /tmp/PASSWORD file doesn't exist at the the time docker image starts, so if you trying to mount new password make sure the `$(pwd)/PASSWORD` is resolved to correct file. If you trying to grab the password from the image  you will need to do to through `docker exec` command instead

**Comment by shareauto** [comment]
Thank you guys, the PASSWORD file on my local doesn't exist while starting the image. That's why it failed. Now It's working fine. Thank you once again.

**Comment by arturdzm** [comment]
You are welcome. Closing this issue
