### ISSUE TITLE
Script name "modify_password.sh" suggests it will be changed, not merely set.

### ISSUE THREAD

**Issue by scottkurz** [WASdev/ci.docker.websphere-traditional#124]
The **modify_password.sh** script name suggests that the wsadmin password will be changed. 

In fact, whatever is in `/tmp/PASSWORD` will be set via wsadmin.   If that file doesn't exist a new value will be randomly generated into it, but if it does exist that same value will be pushed along.

As I go down the route of doing:

> RUN /work/configure.sh /work/a.py
> RUN /work/configure.sh /work/b.py

it seemed interesting to know that the password remains the same.

So I think it might be worth coming up with a better name.

**Comment by arthurdm** [comment]
Seems reasonable to me.

**Comment by arthurdm** [comment]
PR merged, thanks @scottkurz!
