### ISSUE TITLE
Unable to start server automatically when the container starts.

### ISSUE THREAD

**Issue by shareauto** [WASdev/ci.docker.websphere-traditional#129]
The final step in my Docker file is 

CMD ["/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1"]

It's not kicking off when I run the container. I  have to log in to the container and have to start the server manually. 

Is there anything I am missing?

**Comment by arturdzm** [comment]
You should user /work/start_server script, it does some extra steps such piping output to docker logs

**Comment by shareauto** [comment]
@arturdzm  I did use "USER was" but even though it not kicking off the server.  And I did change the CMD as

CMD /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1

but no luck.... :(

**Comment by arturdzm** [comment]
Here very simple docker file, no need to override CMD, unless you are changing to completely different script
```
FROM ibmcom/websphere-traditional
COPY hello.ear /work/config/app.ear
COPY script.py /work/config/script.py
COPY was-config.props /work/config/was-config.props
RUN /work/configure.sh
```

**Comment by arturdzm** [comment]
Closing for now, re-open if needed
