### ISSUE TITLE
Question about properties-based configuration

### ISSUE THREAD

**Issue by kgibm** [WASdev/ci.docker.websphere-traditional#148]
The main README uses this example for a properties-based configuration update:

```
[...]
ResourceId=Cell=!{cellName}:Node=!{nodeName}:Server=!{serverName}:JavaProcessDef=ID#JavaProcessDef_1183122130078:JavaVirtualMachine=ID#JavaVirtualMachine_1183122130078
[...]
```

I'm just curious if the `JavaProcessDef_1183122130078` is required? Is that just what happens to be the unique ID embedded into the image and therefore the one that needs to be updated?

**Comment by arthurdm** [comment]
@arturdzm ^

**Comment by arturdzm** [comment]
In this case its optional
ResourceId=Cell=!{cellName}:Node=!{nodeName}:Server=!{serverName}:JavaProcessDef=:JavaVirtualMachine=
Should also work. The specific IDs are required in case there are multiple objects of the same type, eg DataSources

**Comment by kgibm** [comment]
Thanks.
