### ISSUE TITLE
Documentation update for Logging

### ISSUE THREAD

**Issue by rtclauss** [WASdev/ci.docker.websphere-traditional#153]
In the [README.md](https://github.com/WASdev/ci.docker.websphere-traditional/blob/master/README.md) under [Logging Configuration](https://github.com/WASdev/ci.docker.websphere-traditional/blob/master/README.md#logging-configuration) the line
`ENV ENABLE_BASIC_LOGGING = true`
should read:
`ENV ENABLE_BASIC_LOGGING=true`
or
`ENV ENABLE_BASIC_LOGGING  true`

with a space between the equals sign it makes the value of `ENABLE_BASIC_LOGGING` to the string literal `= true` which causes HPEL logging to be enabled instead of the basic logging.

**Comment by arthurdm** [comment]
Great catch @rtclauss - thank you!

I fixed that now.
