### ISSUE TITLE
Production license

### ISSUE THREAD

**Issue by caic** [WASdev/ci.docker.websphere-traditional#171]
Hello,

I found here how to upgrade Liberty license:

https://github.com/WASdev/ci.docker/tree/master/ga/production-upgrade

Is it valid for Traditional as well?

Thank you!

**Comment by arthurdm** [comment]
Hi,

The good news is that as long as you have traditional WAS entitlement you can use the Docker Hub images in production, without having to make any changes.  This is only for v9.x images.

If for some reason you wanted to build your own image with your production binary, you can follow these instructions: https://github.com/WASdev/ci.docker.websphere-traditional/tree/master/docker-build/9.0.0.11#how-to-build-this-image

Even for Liberty, this `upgrade path` is really not needed - it's just a matter of preference.

**Comment by caic** [comment]
Thank you very much!
