### ISSUE TITLE
slow startup of tWAS container in ICP

### ISSUE THREAD

**Issue by donbourne** [WASdev/ci.docker.websphere-traditional#176]
First launch of traditional WAS container after deployment takes about 15 minutes to reach "ready for e-business".  "Scale up images" take roughly 4 minutes.

THEORY: seems to be 5 java processes running at same time during startup, and only the logViewer limits its memory usage with -Xmx.  So it may be a memory problem related to change in default setting for java 8 to use -XX:+UseContainerSupport by default (see https://www-01.ibm.com/support/docview.wss?uid=swg21672834#java8sr5fp26)
	
Some of the java processes running concurrently at startup:
- com.ibm.ws.logging.hpel.viewer.LogViewer
- com.ibm.ws.management.tools.WsServerLauncher
- com.ibm.ws.postinstall.runConfigActions.RunConfigActions -startServer
- com.ibm.wsspi.bootstrap.WSPreLauncher

helpful to run this from inside the container during startup:
watch 'ps -C java -o pid,cmd,rss,time'

**Comment by jwalcorn** [comment]
I found I had to increase the memory limit for the deployment (in the yaml) a lot, compared to what I use for Liberty.  That's probably stating the obvious, but just in case - upping that like from 256MB to 1GB make my tWAS container start a LOT faster (in OpenShift, in my case)

**Comment by gmarcy** [comment]
that seems comparable to our experience with the helm chart, was-liberty uses:

resources:
  constraints:
    enabled: false
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 4000m
    memory: 2Gi

and was-traditional uses:

resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 10Gi

or a 4x to 5x increase in the memory limit

**Comment by gmarcy** [comment]
Closing issue since the current helm charts increased the memory limits for tWAS.
