### ISSUE TITLE
websphere-traditional:9.0..0.9-traditional java.security.cert.CertificateExpiredException

### ISSUE THREAD

**Issue by albertodf** [WASdev/ci.docker.websphere-traditional#186]
The container run is showing the following error:

WASX7023E: Error creating "SOAP" connection to host "localhost"; exception information: com.ibm.websphere.management.exception.ConnectorNotAvailableException: [SOAPException: faultCode=SOAP-ENV:Client; msg=Error opening socket: java.io.IOException: Exception during sslSocket.startHandshake: com.ibm.jsse2.util.h: PKIX path validation failed: java.security.cert.CertPathValidatorException: The certificate expired at Fri Nov 15 18:09:53 UTC 2019; internal cause is:
java.security.cert.CertificateExpiredException: NotAfter: Fri Nov 15 18:09:53 UTC 2019; targetException=java.lang.IllegalArgumentException: Error opening socket: java.io.IOException: Exception during sslSocket.startHandshake: com.ibm.jsse2.util.h: PKIX path validation failed: java.security.cert.CertPathValidatorException: The certificate expired at Fri Nov 15 18:09:53 UTC 2019; internal cause is:
java.security.cert.CertificateExpiredException: NotAfter: Fri Nov 15 18:09:53 UTC 2019]

**Comment by gmarcy** [comment]
can you move up to one of the more recent images, at least 9.0.0.11 or newer and confirm that this is still an issue ?

**Comment by albertodf** [comment]
sorry, is the 9.0.0.9-profile still in maintenance? what the differences between a version 9.0.0.X and the 9.0.0.X-profile?

**Comment by gmarcy** [comment]
As of today, 9.0.0.11, 9.0.5.0 and 9.0.5.1 are the current images.

From the page at https://hub.docker.com/r/ibmcom/websphere-traditional

> Images
> 
> We are keeping N-2 images in this repository, which means the current fixpack and the previous two.
> 
> The profile image contains the IBM WebSphere Application Server for Developers with the profile already created. With this image, when the container is started the server is started.

**Comment by holatuwol** [comment]
@gmarcy : None of the versions you listed (9.0.0.11, 9.0.5.0, 9.0.5.1) have `profile` images on DockerHub. Does that mean that IBM no longer plans to publish images with a profile already created, or are those images being published somewhere outside of DockerHub?

**Comment by gmarcy** [comment]
All images come with a default profile - AppSrv01

**Comment by savas127** [comment]
Is ibmcom/websphere-traditional:8.5.5.14-profile image still supported? SSL Certificate is expired in it too.

**Comment by gmarcy** [comment]
as mentioned above, we support the latest release and the two previous releases.  8.5.5.14 is not a supported release.
