### ISSUE TITLE
Invalid username and password in WAS admin console

### ISSUE THREAD

**Issue by akrachakonda** [WASdev/ci.docker.websphere-traditional#187]
Pull the docker websphere-traditional image and ranned it. 
Extracted the password from /tmp/PASSWORD file
Started the container and WAS console is up
But when i keyin the wsadmin and password --> shows invalid user and password

**Comment by 3V1L-C0D3-M0NK3Y** [comment]
I ran 
docker run  -i -t --name was-server -h was-server  -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:latest
then 
docker exec  was-server_test cat /tmp/PASSWORD

**Comment by akrachakonda** [comment]
Thanks. It works.
