### ISSUE TITLE
include apt-get update

### ISSUE THREAD

**Issue by lrk** [WASdev/ci.docker.websphere-traditional#21]
in file ci.docker.websphere-traditional/network-deployment/install/Dockerfile.prereq

replace 
RUN apt-get install -y unzip wget
with 
RUN apt-get update -y &&  apt-get install -y unzip wget

to prevent 
`Status: Downloaded newer image for ubuntu:14.04
 ---> 90d5884b1ee0
Step 2 : MAINTAINER Kavitha Suresh Kumar <kavisuresh@in.ibm.com>
 ---> Running in 5f13cf9ddb9a
 ---> 7f93c06538b9
Removing intermediate container 5f13cf9ddb9a
Step 3 : RUN apt-get install -y unzip wget
 ---> Running in d15aa6ccaadb
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package unzip
E: Unable to locate package wget
`

**Comment by davidcurrie** [comment]
@lrk - thanks for highlighting this. Fixed under https://github.com/WASdev/ci.docker.websphere-traditional/pull/22. Any other feedback is welcome.
