### ISSUE TITLE
Iframe isnt working after mapping in nginx

### ISSUE THREAD

**Issue by fadel09** [WASdev/ci.docker.websphere-traditional#301]
I mapped my ip to 192.168.1.13:9443 in nginx but when I access my application it is giving

Refused to frame 'https://192.168.1.13:9443/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'". My configuration in nginx to map it is: location /{ proxy_pass  https://192.168.1.13:9443; }

**Comment by covener** [comment]
I think you want to configure nginx to either replace references to the backend host with the frontend host, or configure it to pass $WSRH to the backend:

```
proxy_set_header "$WSRH" $host;
```

**Comment by fadel09** [comment]
It still giving me the same error

**Comment by covener** [comment]
I don't think there is anything specific to the container image here. You'll have to debug how your browser has any idea about your backend IP address.

**Comment by fadel09** [comment]
My backend is printing https://192.168.1.13:9443/ however my front have the ip 192.168.1.13

**Comment by fadel09** [comment]
I added proxy_set_header Host $host; and it worked. Thanks for your time
