### ISSUE TITLE
ibmcom/websphere-traditional:8.5.5.9-profile Won't start

### ISSUE THREAD

**Issue by ernani** [WASdev/ci.docker.websphere-traditional#33]
I am trying to run the image and it doesn't start the WAS, is this expected?
I've also tried with ibmcom/websphere-traditional:8.5.5.9-install and that one doesn't even has the server profile setup, so I am using the supposed correct image, is this just featured in latest?
Thanks in advance!

**Comment by davidcurrie** [comment]
As per the documentation, the images with the install tags do not have a profile created. Can you say more about the way in which the profile image is not working for you?

I've just run the following:
`docker run --name test -h test -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:profile`

After waiting for the 'open for e-business' message in the logs, I could then access the admin console at https://localhost:9043/ibm/console using the user wsadmin and the password obtained from `docker exec test cat /tmp/PASSWORD`.

**Comment by ernani** [comment]
Have you tried with the version tag 8.5.5.9-profile tag? Here I see no logs at all.
Here is the command I am using:
`docker run --name was-eight -h was-eight -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:8.5.5.9-profile`

**Comment by ernani** [comment]
Nevermind, it works fine, for some reason if I don't run with -d it won't kickstart WAS, is there a reason for this? I am new to docker so that could be the reason I am bugging you guys...

This is the command I was trying to run previously:
`docker run --name was-eight -h was-eight -e UPDATE_HOSTNAME=true -p 9043:9043 -p 9443:9443 -i -t ibmcom/websphere-traditional:8.5.5.9-profile /bin/bash`

I want WAS to be on the same hostname as my machine if possible. Or could assign it some other IP address on my local network if possible.

**Comment by ernani** [comment]
Nevermind I am putting a reverse proxy on top of the IP to make the bridge, it is the quickest way, thanks a lot!

**Comment by davidcurrie** [comment]
@ernani - the problem with your foreground example is the `/bin/bash` appended on this end. This is the command that's going to get run when the container gets started rather than the default `/work/start.sh` script that actually starts the server. Use the `--net host` option if you want to reuse the Docker host's network stack (if you're running Docker in a VM this will obviously still be the network stack for the VM).
