### ISSUE TITLE
WebSphere traditional 8.5.5.9 with JDK 8

### ISSUE THREAD

**Issue by deathcoder** [WASdev/ci.docker.websphere-traditional#38]
Hi, i'm having troubles changing the jdk provided with the image, i need to run WebSphere with JDK 8 can you please tell me if it's possible to do it? and if it is also tell me what i have to do

thank you

**Comment by davidcurrie** [comment]
Hi - given your comments, presumably you are trying to build your own base or ND images? The 8.5.5.9 image on Docker Hub and the corresponding build scripts here already use an 8.0 JRE. You'll need to make modifications in two places. Firstly, in Dockerfile.prereq you'll need to wget the appropriate zips and then modify the install package listed on the imcl command. Secondly, in Dockerfile.install you'll need to modify the call to manageSDK to switch to the newer JRE. Hope that helps.

Regards
David

**Comment by davidcurrie** [comment]
Closing - please reopen if you need further assistance.
