### ISSUE TITLE
Volume Usage Support

### ISSUE THREAD

**Issue by crmarques** [WASdev/ci.docker.websphere-traditional#47]
It could be added support for volume usage in order to separate the binary from dynamic data as profile configuration.

**Comment by ZhukovAlexey** [comment]
@crmarques in create_profile script you can see the profile path.

It's a /opt/IBM/WebSphere/AppServer/profiles/$PROFILE_NAME

So you can use docker run ... -v local_path:/opt/IBM/WebSphere/AppServer/profiles to save your profiles outside of container.

**Comment by davidcurrie** [comment]
@crmarques - what are you looking for here? as @ZhukovAlexey states you can expose the profile externally. See also this YouTube video: https://www.youtube.com/watch?v=OU0pELBTJk8&t=8s  I would not want to explicitly add a VOLUME to the image as not everyone is going to want this outside of the container.

**Comment by crmarques** [comment]
Thank you @ZhukovAlexey e @davidcurrie for your responses. I imagined this separation (profile dir from binaries), but maybe it would be the case to indicate in the README file, for example. Or just link this youtube video. It would help new users. 

I did not understand why not everyone is going to want a volume from a mutable data besides the test scenario. Maybe it's because my lack of imagination kkkkk

My other question is whether separate only the profile dir is enough. For instance, the properties dir has files that are built when a profile is created (fsdb/* and profileRegistry.xml) that willl be lost when changing the image.

Thank you again for the comments!

**Comment by ZhukovAlexey** [comment]
The best way as I consider is having all your application deployment steps in Dockerfile, so you can build your application at any time from scratch.

In that case not only WAS is in container, but all parts of your application. And you can build your application wherever you want.

Buthe even having only binaries I'm container make sense and make deployment easier. 

So I' wondering to know how to deal with other files which isn't in profile folder such as profileRegistry.xml too.

**Comment by arthurdm** [comment]
Hi guys - as noted by @ZhukovAlexey, the best practice is to have all the steps in the Dockerfile, including application configuration and deployment.

Consider the scenario where this container is running in Kubernetes (or another container orchestration framework) and it fails - a new one will be built back up, so if the image is not self-contained (i.e. if you had to run some manual steps after the deployment) you won't be able to benefit from this auto-restart..which is not desirable in production.

Closing this - please re-open if there are lingering questions/issues.
