### ISSUE TITLE
Correct nd custom example image name

### ISSUE THREAD

**Issue by dacleyra** [WASdev/ci.docker.websphere-traditional#50]
docker run --name custom1 -h custom1 --net=cell-network -e PROFILE_NAME=Custom01 -e NODE_NAME=CustomNode01 -e DMGR_HOST=dmgr -e DMGR_PORT=8879 -d custom

should be

docker run --name custom1 -h custom1 --net=cell-network -e PROFILE_NAME=Custom01 -e NODE_NAME=CustomNode01 -e DMGR_HOST=dmgr -e DMGR_PORT=8879 -d websphere-traditional:custom

**Comment by davidcurrie** [comment]
Good spot! Fixed.
