### ISSUE TITLE
Issue with file permissions

### ISSUE THREAD

**Issue by kevinpauli** [WASdev/ci.docker.websphere-traditional#54]
When attempting to build the `dmgr` image I am getting 

`java.io.FileNotFoundException: /opt/IBM/WebSphere/AppServer/configuration/org.eclipse.osgi/.manager/.fileTableLock (Permission denied)`

Could this be because in websphere-traditional:nd-install (the base image) after the ADD of the tar, the file permissions are all `drwxr-xr-x 3 root root` and the USER has been set to `was`?

FYI I was able to workaround it by removing the section that creates the `was` user, which makes everything execute as root.

**Comment by davidcurrie** [comment]
Hi Kevin - you shouldn't see this if the tar was created as the `was` user as the ADD command unpacks as root (regardless of the current user) so you should get the same user permissions as the files in the tar. It will take me a while to verify that this is working as designed but if you could take a look at what permissions are being created in your tar file that would be interesting.

**Comment by kevinpauli** [comment]
Crap, sorry.  Yeah in my prereq project (the one that installs websphere and builds the tar) I forgot I modified it to do the install as root.  So the files in the tar are also root's.  Nevermind.
