### ISSUE TITLE
output all log files to Docker logs

### ISSUE THREAD

**Issue by dkirrane** [WASdev/ci.docker.websphere-traditional#56]
Docker logs only shows the `startServer.log` but there are other logs like `SystemOut.log` and any other log files. Can these be redirected somehow to Docker logs

**Comment by davidcurrie** [comment]
Hi - what image are you using? You should see the output from the server start initially but once the server startup is complete it then tails SystemOut.log and SystemErr.log.

**Comment by arthurdm** [comment]
Closing as `answered`.
