### ISSUE TITLE
PASSWORD GERNERATE

### ISSUE THREAD

**Issue by quangvi282** [WASdev/ci.docker.websphere-traditional#57]
all version when i run docker, has problem when i see log /work/modify_password: line 17: /tmp/PASSWORD: Is a directory
I can't get password , so please help me fix it

**Comment by davidcurrie** [comment]
Are you trying to mount a password file in? Typically I see that message when I've tried to mount a volume but the location on the host did not exist at which point Docker just creates an empty directory rather than a file.

**Comment by quangvi282** [comment]
i run docker like document
docker run --name test -h test -v $(pwd)/PASSWORD:/tmp/PASSWORD \
  -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:install

before i created file PASSWORD , but I saw logs above.

**Comment by davidcurrie** [comment]
What platform are you running this on? The `$(pwd)/PASSWORD` path needs to be accessible to wherever the Docker engine is running.

**Comment by quangvi282** [comment]
debian

**Comment by davidcurrie** [comment]
Just checked the command and it works for me on my RHEL box. Is PASSWORD definitely in the current directory and is it going to be readable by the user that WAS is running as in the container?

If you run the following you should be able to see your password:
```
docker run --name test -h test -v $(pwd)/PASSWORD:/tmp/PASSWORD \
-p 9043:9043 -p 9443:9443 -it ibmcom/websphere-traditional:install bash
cat /tmp/PASSWORD
```

**Comment by quangvi282** [comment]
Please check on debian, i think platform not influence

**Comment by davidcurrie** [comment]
I agree - I don't believe Debian should make a difference vs RHEL and I don't have access to a Debian box to try. What do you see if you run the container with bash as above?

**Comment by davidcurrie** [comment]
Also, try replacing $(pwd) with the full path to the PASSWORD file.

**Comment by quangvi282** [comment]
all is not work

**Comment by davidcurrie** [comment]
OK - let's try something really simple. Does the following work?
```
docker run --rm -v $(pwd)/PASSWORD:/tmp/PASSWORD ubuntu cat /tmp/PASSWORD
```

**Comment by quangvi282** [comment]
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
Digest: sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028
Status: Downloaded newer image for ubuntu:latest
cat: /tmp/PASSWORD: Is a directory

**Comment by jamiecoleman92** [comment]
I have tried the instructions mentioned above and for me it all works perfectly on Ubuntu 16.0.04. I was able to successfully mount the password file and log into the admin console with a custom password. It seems you may have some permission issues on your directory. I did the above using a freshly created Ubuntu 16.04 virtual machine.

**Comment by davidcurrie** [comment]
OK - so the problem is not specific to our websphere-traditional image. It occurs to me that I should ask where your Docker engine is relative to your Docker CLI. Is the engine running natively on your Debian host? Or are you running it remotely or under some form of virtualization (VirtualBox/KVM/...)?

**Comment by quangvi282** [comment]
i'm using old version docker, so maybe that's problem. which docker do you use ?

**Comment by quangvi282** [comment]
i updated docker-ce but still like above, i use debian6 on vmware (vphere)

**Comment by quangvi282** [comment]
i updated docker-engine to dokcer-ce and problem is solved

**Comment by davidcurrie** [comment]
Hmm - I'm not sure why that should make a difference but glad to hear the problem is resolved anyway!

**Comment by shareauto** [comment]
I have the same problem, unable to get the password file from /tmp/PASSWORD

There is no password under the /tmp/PASSWORD, Please find the below command output for your reference.


[root@fsr3vlwaspoc1 ~]#‌ docker ps

CONTAINER ID    IMAGE                 COMMAND         CREATED       STATUS       PORTS                      NAMES

18321f1d8492    ibmcom/websphere-traditional:latest  "/work/start_serve..."  2 hours ago     Up About an hour  0.0.0.0:9043->9043/tcp, 0.0.0.0:9443->9443/tcp  test

[root@fsr3vlwaspoc1 ~]#‌ docker exec test cat /tmp/PASSWORD

cat: /tmp/PASSWORD: Is a directory

[root@fsr3vlwaspoc1 ~]#‌
