### ISSUE TITLE
Problem starting websphere-traditional:profile

### ISSUE THREAD

**Issue by CapKenR** [WASdev/ci.docker.websphere-traditional#62]
I'm using the command `docker container run --name websphere -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:profile` to successfully start WebSphere on my Windows 10 laptop running Docker for Windows using Linux containers. (It takes a LONG time, 1 1/2 hours, to start but it does start and works.)

I've tried the same command on two separate Linux servers (one Ubuntu 16.04 and the other RHEL 7.3) but in both cases it seems to hang in the same place. The last line I see in the logs is:

`[9/13/17 14:55:41:616 UTC] 00000033 FileRepositor A   ADMR0016I: User defaultWIMFileBasedRealm/server:DefaultCell01_DefaultNode01_server1 modified document cells/DefaultCell01/security.xml.`

On my laptop, the following line is next in the log files:

`[9/13/17 16:09:59:951 UTC] 000000b4 ActionServlet I org.apache.struts.action.ActionServlet init inside init....`

As you can see on my laptop it takes 1:15 between the two lines so it's not unreasonable to expect it to take quite a while on the Linux servers as well. However, I have left them up over night and they're still not running.

Looking through container logs and under the /opt/IBM/WebSphere/ directory on the running containers I don't see any errors. Any ideas?

**Comment by arturdzm** [comment]
Could you try using latest images, the repository was re-worked and many scripts improved.
As for slow star on your Windows 10 machine it could be because the docker is not running with virtualization enabled. Latest Docker engine on Windows 10 uses Hyper-V to create it's VMs

**Comment by shareauto** [comment]
I am building FROM ibmcom/websphere-traditional:latest to build our custom image.
looks like start_server.sh script needs to be fixed, updatehostname.sh script doesn't exist. but that's being called from start_server.sh script.

**Comment by arturdzm** [comment]
I've updated start_server to fix update_hostname call
