### ISSUE TITLE
Support for WAS v7?

### ISSUE THREAD

**Issue by GedLawrenson** [WASdev/ci.docker.websphere-traditional#64]
Hi,

Is there any plan to provide Docker images for WAS v7?

I am trying to build an IBM WebSphere Commerce environment using Docker. WebSphere Commerce still relies on WAS v7, FP 43.  

I assume the answer is "No" as it is probably too old to be used widely, but I thought I would ask anyway.

Thanks, Ged.

**Comment by davidcurrie** [comment]
Hi Ged

You assume correctly. We declared support from 8.5.5 onwards and there are no plans to extend that backwards. That's not to say that you won't get it to work - just that you won't see us building images and you won't get support from IBM.

Regards
David
