### ISSUE TITLE
./build results in 

### ISSUE THREAD

**Issue by espre05** [WASdev/ci.docker.websphere-traditional#65]
Sending build context to Docker daemon  171.6MB
Step 1/5 : FROM ubuntu:16.04
 ---> 2d696327ab2e
Step 2/5 : RUN apt-get update && apt-get install -y unzip
 ---> Using cache
 ---> 6fe2ca5427b0
Step 3/5 : COPY agent.installer.linux.gtk.x86_64_*.zip /tmp/
 ---> Using cache
 ---> 7335cfca3008
Step 4/5 : RUN unzip -qd /tmp/im /tmp/agent.installer.linux.gtk.x86_64_*.zip   && /tmp/im/installc -acceptLicense -accessRights nonAdmin     -installationDirectory "/opt/IBM/InstallationManager"      -dataLocation "/var/ibm/InstallationManager" -showProgress   && rm -rf /tmp/agent.installer.linux.gtk.x86_65_*.zip /tmp/im
 ---> Using cache
 ---> 45032a6db5be
Step 5/5 : ENV PATH /opt/IBM/InstallationManager/eclipse/tools:$PATH
 ---> Using cache
 ---> e956d7e1bf79
Successfully built e956d7e1bf79
Successfully tagged installation-manager:latest
Starting install of TWAS version: 1.0
tar: Removing leading `/' from member names
**tar: /opt/IBM/WebSphere/AppServer: Cannot stat: No such file or directory**
tar: Exiting with failure status due to previous errors
ML02:developer pro$ 

May need to update docker file with mkdir?

**Comment by reneburghardt** [comment]
Did you solve the issue?

Got the exact same error and what I did was creating the directory, but then later in `.../developer/profile/Dockerfile --> RUN /work/create_profile` I get the following error message:

Step 10/16 : RUN /work/create_profile
 ---> Running in 7a92fa53c93c
Creating profile ....................
/work/create_profile: line 19: /opt/IBM/WebSphere/AppServer/bin/manageprofiles.sh: No such file or directory
The command '/bin/sh -c /work/create_profile' returned a non-zero code: 127

Where am I supposed to get the AppServer-directory?

**Comment by arthurdm** [comment]
hi @espre05 @reneburghardt - can you guys please try the new instructions and dockerfile? https://github.com/WASdev/ci.docker.websphere-traditional/tree/master/docker-build#building-the-image    It's now much easier to build the image.

**Comment by reneburghardt** [comment]
@arthurdm Hey thanks for your reply. I went for another solution and unfortunately won't have time to check the new instructions in the next time, sorry.
