### ISSUE TITLE
Failure occured while attempting to Importing Config Archive

### ISSUE THREAD

**Issue by rbernardino** [WASdev/ci.docker.websphere-traditional#66]
Hi David, 

I am using the network deployment WAS. I was able to build images up to *:install. However, I'm having problems when building the images for, say dmgr and appsrv. For example, here's what I got for appsrv,

`The translated exception message is: The following error occurred while executing this line:
/opt/IBM/WebSphere/AppServer/profileTemplates/default/actions/scripts/importExternalLogs.xml:30: Failure occured wh
ile attempting to Importing Config Archive: /opt/IBM/WebSphere/AppServer/profileTemplates/default/configArchives/Ap
pSrv.car into profile.`

I did see that the file is there:
`was@552f09386c53:/$ ls -ltr /opt/IBM/WebSphere/AppServer/profileTemplates/default/configArchives/AppSrv.car
-rw-r--r-- 1 was was 1026781 Oct  6 06:00 /opt/IBM/WebSphere/AppServer/profileTemplates/default/configArchives/AppSrv.car
`

Have you encountered that same problem before?

Thanks!

**Comment by rbernardino** [comment]
By the way, I am using an Ubuntu 14.04 VM running on VirtualBox as my docker host. It has 1 cpu and 1gb of memory.

```
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by ernani** [comment]
Apparently something is adding up a space in that file. I haven't experienced that error though since I am using an older version of WAS and Docker.

**Comment by rbernardino** [comment]
Hi Ernani,

So is it possible that I am running out of disk space while I'm building that image? I am using the latest version of Docker CE and a trial version of WAS ND 8.5.5. I'm pretty sure I have enough disk space on the   host machine but I am not sure how docker is managing space when building an image. 
Thank you!

**Comment by ernani** [comment]
Does the error outputs this AppServ.car with a space?

`onfigArchives/Ap pSrv.car` ?

**Comment by rbernardino** [comment]
The output actually does not contain a space. That was just a result of me copying and pasting the error messages. However, after some trial and errors, adding these few lines in the `websphere-traditional:nd-install ` image solved the problem and allowed me to build `dmgr ` and  `appserver ` images w/o errors.

`unlink /bin/sh` 
`ln -s /bin/bash /bin/sh`

Here is the Dockerfile.install that I used inside network-deployment/install.

```
FROM ubuntu:16.04

ARG user=was
ARG group=was
RUN groupadd $group && useradd $user -g $group -m \
    && mkdir /work && chown -R $user:$group /work \
    && unlink /bin/sh \
    && ln -s /bin/bash /bin/sh
USER $user

ADD was.tar /

ENV PATH /opt/IBM/WebSphere/AppServer/bin:$PATH
```

This article was indeed a great help. 
_http://www.torkwrench.com/2009/05/04/getting-websphere-portal-to-install-on-ubuntu/_

**Comment by ernani** [comment]
Awesome! Congrats!
