### ISSUE TITLE
How to install Java 7 SDK? Please help.

### ISSUE THREAD

**Issue by kjs1028x** [WASdev/ci.docker.websphere-traditional#72]
In the comments section on https://hub.docker.com/r/ibmcom/websphere-traditional/, quite a few of us are asking how to add Java 7 SDK to the WAS 8.5.5.X docker container. I've installed imcl on the 8.5.5.10 docker container and tried installing Java 7 SDK but I'm getting the same error as the other people.

```
/opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.IBMJAVA.v70_7.0.4001.20130510_2103 -repositories /opt/IBM/WebSphere/AppServer/temp/sdk -acceptLicense

ERROR: The installation package 'IBM WebSphere SDK Java Technology Edition (Optional)' requires components supplied by other packages.
The required components might be supplied by the following installation packages:
Package: WebSphere Application Server Version 8.5
Package: Application Client for IBM WebSphere Application Server Version 8.5
Package: DMZ Secure Proxy Server for IBM WebSphere Application Server Version 8.5
```

I understand that imcl is not aware of the existing WAS installation. How do we workaround this issue? Thanks.

**Comment by davidcurrie** [comment]
You would be better building your own image from scratch. If you follow the instructions at https://github.com/WASdev/ci.docker.websphere-traditional/tree/master/developer you can just modify the versions.csv to specify a different version of Java to install.

**Comment by phreakadelle** [comment]
Hey @davidcurrie ,
i've tried around a little bit and the image works perfectly fine for us. Now i need to setup an image with JDK7 but i dont know which information i need to put in into the version.csv file. How do i find out the correct filenames for JDK7?

**Comment by davidcurrie** [comment]
You can find the list of repositories here:
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.installation.nd.doc/ae/cins_repositories.html

So you'd want on of:
http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IBMJAVA.v70
http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IBMJAVA.v71

Then you need to use `imcl` to find the name of the package within the repository. For example:

```
$ /opt/IBM/InstallationManager/eclipse/tools/imutilsc saveCredential -secureStorageFile /tmp/ssf -userName ... -userPassword ... -url http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IBMJAVA.v71
Successfully saved the credential to the secure storage file.
$ /opt/IBM/InstallationManager/eclipse/tools/imcl listAvailablePackages -repositories http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IBMJAVA.v71 -sSF /tmp/ssf
com.ibm.websphere.IBMJAVA.v71_7.1.0.20140324_2146
com.ibm.websphere.IBMJAVA.v71_7.1.1000.20140723_2109
com.ibm.websphere.IBMJAVA.v71_7.1.2000.20141116_0823
com.ibm.websphere.IBMJAVA.v71_7.1.2010.20150219_1805
com.ibm.websphere.IBMJAVA.v71_7.1.3000.20150528_1959
com.ibm.websphere.IBMJAVA.v71_7.1.3010.20150820_1342
com.ibm.websphere.IBMJAVA.v71_7.1.3010.20151112_0058
com.ibm.websphere.IBMJAVA.v71_7.1.3030.20160224_1952
com.ibm.websphere.IBMJAVA.v71_7.1.3040.20160720_1746
com.ibm.websphere.IBMJAVA.v71_7.1.3060.20161124_1256
com.ibm.websphere.IBMJAVA.v71_7.1.4005.20170626_0531
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.1000.20140723_2109
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.2000.20141116_0823
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.2010.20150219_1805
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3000.20150528_1959
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3010.20150820_1342
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3010.20151112_0058
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3030.20160224_1952
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3040.20160720_1746
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.3060.20161124_1256
com.ibm.websphere.liberty.IBMJAVA.v71_7.1.4005.20170626_0531
```

**Comment by phreakadelle** [comment]
Thanks a lot, David!

**Comment by CuitlahuacTogo** [comment]
> Thanks a lot, David!
> 
> Works perfectly fine for me! Now i have WebSphere 8.5.5.9 with JDK 7.0

I couldn't. Can you show me how did you do it

**Comment by phreakadelle** [comment]
Its pretty good documented here: https://github.com/WASdev/ci.docker.websphere-traditional/tree/master/developer

**Comment by viswa-optimusprime** [comment]
@phreakadelle  - Looks like document removed Do you have  document?
 https://github.com/WASdev/ci.docker.websphere-traditional/tree/master/developer
