### ISSUE TITLE
How to add Python in ibmcom/websphere-traditional container

### ISSUE THREAD

**Issue by unitopia** [WASdev/ci.docker.websphere-traditional#74]
We are trying to add/install Python in ibmcom/websphere-traditional container, but it pops-up the Permisson denied.
We also tried to use owned Dockerfile
# Set the base image to websphere-traditional
FROM docker.io/ibmcom/websphere-traditional

# Expose the default port
EXPOSE 9043/TCP 9080/TCP 443/TCP 80/TCP 389/TCP 5060/TCP 5061/TCP

# Update the repository sources list
RUN apt-get update

################## BEGIN INSTALLATION ######################
# Install python3
RUN apt-get install python3-all

# Update the repository sources list once more
RUN apt-get update
##################### INSTALLATION END #####################

the Permission denied occurred at # Update the repository sources list
RUN apt-get update

How do we workaround this issue? Thanks.

**Comment by davidcurrie** [comment]
You need to set the user back to root in the Dockerfile before you try and install new packages:
```
USER root
```

**Comment by unitopia** [comment]
Thanks David.
This works.

**Comment by arturdzm** [comment]
Looks resolved, closing.
