### ISSUE TITLE
Container stops if server is restarted

### ISSUE THREAD

**Issue by Muotovalio** [WASdev/ci.docker.websphere-traditional#76]
Docker container automatically stops if I stop the server using the stopServer.sh script. I think that is Docker feature. What is recommended practice to restart the server?

**Comment by arthurdm** [comment]
@Muotovalio - by default (unless you override the CMD) the server inside the container is PID 1, so if you exit that process Docker will correctly stop the container.  So you would have to start the container again, which would automatically start the server inside.

**Comment by arthurdm** [comment]
Closing this as `answered`.  If there's still an issue please feel free to re-open.
