### ISSUE TITLE
NoClassDefFoundError: ConfigService

### ISSUE THREAD

**Issue by Muotovalio** [WASdev/ci.docker.websphere-traditional#78]
I get an error java.lang.NoClassDefFoundError: com.ibm.websphere.management.configservice.ConfigService when installing MDM CE using 9.0.0.6-profile. However, I do not get that error when using 8.5.5.12-profile.

**Comment by arthurdm** [comment]
@Muotovalio - have you verified if this error happens when you do the same install in a non-Docker environment?

**Comment by Muotovalio** [comment]
No, I have not. I managed to complete installation using manual steps. So, it could be an issue with IBM Installation Manager + WAS + Docker.

**Comment by arthurdm** [comment]
Thanks.  I will close this issue as this sounds like a better candidate for a PMR, so that L2/L3 can recreate the composed scenario and find out the root cause.
