### ISSUE TITLE
changing administrative port makes console inaccessible

### ISSUE THREAD

**Issue by phreakadelle** [WASdev/ci.docker.websphere-traditional#82]
Hello Team,

maybe its my bad and the issue can be closed quickly: I am running my WAS traditional container and have mapped the administrative port from inside the container 9060 to outside 80. When i am trying to open a browser on my IP on port 80 i get a redirect to port 9060 again and so the console is not showing up. Same occurs with wget

![image](https://user-images.githubusercontent.com/645665/38875568-ee201cb2-425a-11e8-94e0-9e3e7a9295fe.png)

Can you help me how to access the IBM console on a different port outside the container?

**Comment by arthurdm** [comment]
Hey @phreakadelle - I have created a mapping from `80` to `9043` and I have observed that `https://localhost:80/ibm/console/login.do?action=secure` renders fine, but then after entering the credentials I got a redirect back to `https://localhost:9043/ibm/console/login.do?action=secure`, while failed.  But then manually changing the port back to `80` got me access to the admin console page and then everything else worked from there.  

is this the behaviour you're seeing too?

**Comment by phreakadelle** [comment]
Hey @arthurdm Thats not the same behaviour but very similiar. I've tried to browse to "http://localhost:**80**/ibm/console" and got redirected to "http://localhost:**9060**/ibm/console/unsecureLogin.jsp". This fails!

When i try to open "http://localhost:80/ibm/console/unsecureLogin.jsp" and enter the credentials it works.

**Comment by tienhngnguyen** [comment]
Hi @phreakadelle, I would be interested in that image as well :)
I had the same problem, but I fixed this issue by changing the internet WebSphere port meaning that you have to change the websphere port from 9060 to 80 as well that I redirects you to the right port. However, that does not work if using a HA proxy (e.g. OpenShift) in front of WebSphere. I opened another thread for this case https://github.com/WASdev/ci.docker.websphere-traditional/issues/87

**Comment by phreakadelle** [comment]
I've uploaded those WAS traditional images with an insecure profile on DockerHub: https://hub.docker.com/r/psinfra/websphere-traditional/tags/

**Comment by tienhngnguyen** [comment]
What have you changed in that image? Could I see the Dockerfile that image?

**Comment by phreakadelle** [comment]
Here are the source files:
https://github.com/phreakadelle/ci.docker.websphere-traditional

**Comment by tienhngnguyen** [comment]
Thank you :)

2018-05-24 14:37 GMT+02:00 Stephan <notifications@github.com>:

**Comment by tienhngnguyen** [comment]
So basically, you were just disabling the security of the websphere server which enables you to connect via HTTP and not HTTPS in front of the URL?

**Comment by phreakadelle** [comment]
Yes, easily like this.

**Comment by YuLimin** [comment]
docker run --name wasbase -h wasbase -v $(pwd)/PASSWORD:/tmp/PASSWORD -p **9044**:9043 -p **9444**:9443 -d ibmcom/websphere-traditional:install

1. Add two custom properties under WebContainer
trusthostheaderport = true
com.ibm.ws.webcontainer.extractHostHeaderPort = true

2. Add your new ports on Virtual hosts under Environment. such as **9044** under admin_host for admin console and **9444** under default_host for default host that you exposed them.

Finally, we can add these setting into shell and rebuild WAS images for expose customize ports then run smoothly.
