### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by TomazKarer** [WASdev/ci.docker.websphere-traditional#84]
Hi!

I'm trying to add users with wsadmin.sh script during build of image with RUN. Connection type -conntype NONE and command AdminTask.createUser as expected returns error:

`com.ibm.websphere.management.cmdframework.CommandException: com.ibm.websphere.management.cmdframework.CommandException: Command createUser does not support localmode `

And -conntype SOAP returns error: 

`WASX7023E: Error creating "SOAP" connection to host "localhost"; exception information: com.ibm.websphere.management.exception.ConnectorNotAvailableException: [SOAPException: faultCode=SOAP-ENV:Client; msg=Unable to find a valid IP for host `localhost``

I have the same problem using ENTRYPOINT.

It there no way of creating users? Should it be done only after the container has started?

**Comment by arturdzm** [comment]
If you need to run scripts that require live server connection (SOAP) then server needs to be started.
Best way to do it now is to use configure.sh script and point to to your jython file. Other option is to drop it in and let configure.sh pick it up automatically during docker build

**Comment by arturdzm** [comment]
Closing for now. Re-open if needed.
