### ISSUE TITLE
not able to access was console using 9043

### ISSUE THREAD

**Issue by kusumat** [WASdev/ci.docker.websphere-traditional#91]
Ran docker container with 
docker run --name test -h test -e UPDATE_HOSTNAME=true -p 9043:9043 -p 9443:9443 -d \
  ibmcom/websphere-traditional:9.0.0.7-profile

But i am unable to connect to console with 9043. But i am able to ping and telnet . Is there any explicit setting do i need to take care

**Comment by kusumat** [comment]
> profile

ofile

**Comment by YuLimin** [comment]
1. You should use https:// NOT http for access WAS admin console.

2. and you can run "docker logs test" to find what's the exception on SystemOut.log

3. try to login test WAS instance to find more logs issued by "docker exec -it test bash" command.
cd /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/logs
......

**Comment by arturdzm** [comment]
Console should be accessible at https://localhost:9043/ibm/console

Closing. Re-open if needed
