### ISSUE TITLE
issue while running manageprofile

### ISSUE THREAD

**Issue by ghost** [WASdev/ci.docker.websphere-traditional#92]
Hello,

I have created a container using my own image that contains the instructions to install WAS Base 8.5.5.13 binaries and was sdk install. When I ran manageprofiles command inside that container there is no errors or logs but at the same time the JVM is not getting created .Any idea? We were working with IBM for the past two months for this issue and now they suggested us to create an issue ID here.

**Comment by bensonlatibm** [comment]
Hi,  

What specific manageprofiles command are you trying?

**Comment by bnymwas** [comment]
Hi,

This is the command am trying to run.

/opt/app/was/WAS8.5_BASE/bin/manageprofiles.sh -create -debug -profileName WASBASE_JVM1 -startingPort 15000 -profilePath /opt/app/was/WASBASE_JVM1 -templatePath /opt/app/was/WAS8.5_BASE/profileTemplates/default

**Comment by bensonlatibm** [comment]
After looking at this, I am able to reproduce this on my own build.

Can you try the following as a diagnostic step?

ls -al /bin/sh

If that points to /bin/dash, change the link to /bin/sh

e.g.
ln -sf /bin/bash /bin/sh

and then retry the manageprofiles command.

Alternatively in the Docker.v855.prereq file, add the following lines before ARG USER=was

RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash

**Comment by bnymwas** [comment]
Hi,

I tried the step which was suggested. Still no luck. And also we are not using the docker file from IBM. We have created one on our own based on the steps from IBM.



Thanks,
Vinodhini Vijayakumar
TSG – Application Platform and Services - Web Hosting Services and DevOps
BNY Mellon Technology
Tidel Park, Chennai, India.
Office: +1-646-782-2657
Email: Vinodhini.Vijayakumar@bnymellon.com<mailto:Vinodhini.Vijayakumar@bnymellon.com>

**Comment by arthurdm** [comment]
hi @bnymwas - unfortunately we're no longer supporting the Dockerfiles for pre-v9 WAS.   Can you please try out the new v9 images?

**Comment by shareauto** [comment]
@arthurdm I did try with V9 images same as @bnymwas , but I too face the same problem....

**Comment by bensonlatibm** [comment]
@shareauto, @bnymwas, when I saw this, the Docker container was configured to use the dash shell instead of bash:
you can check by running (inside the docker container)
ls -al /bin/sh

If that points to /bin/dash, change the link to /bin/sh

To change this to bash instead of dash, run the following inside the docker container.
ln -sf /bin/bash /bin/sh

Does that work?

**Comment by leochr** [comment]
Closing issue as per the originator's request.
