### ISSUE TITLE
Errors trying to build this image

### ISSUE THREAD

**Issue by cthigh** [WASdev/ci.docker.websphere-traditional#94]
I went down the path of trying to build the ci.docker.websphere-traditional/developer image locally and hit 2 problems.  (I later realized that I didn't need to be doing this but wanted to share what I hit.)

1. https://github.com/WASdev/ci.docker.websphere-traditional/blob/master/developer/im/Dockerfile
contains the line:
RUN unzip -qd /tmp/im /tmp/agent.installer.linux.gtk.x86_64_*.zip \
  && /tmp/im/installc -acceptLicense -accessRights nonAdmin \
    -installationDirectory "/opt/IBM/InstallationManager"  \
    -dataLocation "/var/ibm/InstallationManager" -showProgress \
&& rm -rf /tmp/agent.installer.linux.gtk.x86_65_*.zip /tmp/im

The issue here is in the clean up rm -rf /tmp/agent.installer.linux.gtk.x86_65_*.zip doesn't match the original file name.  NOTE: **65** vs **64**. 

2. The second issue was related the IM installer I downloaded. I followed the link in the instructions to get `An IBM InstallationManager install .zip for x86 64-bit Linux (agent.installer.linux.gtk.x86_64_*.zip)` - The link took me to http://www-01.ibm.com/support/docview.wss?uid=swg27025142 and I downloaded agent.installer.linux.gtk.x86_64_1.6.1000.20121109_1537.zip which is very old.  With that IM, I get the following error:

```
00:00.39 ERROR [main] com.ibm.cic.agent.internal.application.HeadlessApplication run
  
  {IM install directory}/tools/imcl:
  Problem in command line: -toolId imcl -accessRights nonAdmin -silent -showProgress -acceptLicense install com.ibm.websphere.ILAN.v90_9.0.8.20180530_1827 com.ibm.java.jdk.v8 -repositories http://www.ibm.com/software/repositorymanager/V9WASILAN -installationDirectory /opt/IBM/WebSphere/AppServer -secureStorageFile /tmp/credentials -preferences com.ibm.cic.common.core.preferences.preserveDownloadedArtifacts=false
  Unrecognized command line argument "-secureStorageFile".
```
Some updates on what IM level to get would be useful and where to get it.

3. It would have been good if https://hub.docker.com/r/ibmcom/websphere-traditional/ provided simple examples of a Docker file to build a modified tWAS image.  That's what I was really looking to do, but ended down this trail.

**Comment by patricktiu** [comment]
You should always use the latest IM level (currently 1.8.9.1) available in http://www-01.ibm.com/support/docview.wss?uid=swg27025142. 

Also, the ***-secureStorageFile*** option is only available in IM 1.6.2 and up.

**Comment by patricktiu** [comment]
I am also working on a new Dockerfile to create tWAS V90 image in my own fork.  You can try it and let me know any feedback.

https://github.com/patricktiu/ci.docker.websphere-traditional/tree/development/v90

**Comment by arthurdm** [comment]
hi @cthigh - have you tried the build with the latest docs?   I have been building them successful after we switched to the new Dockerfiles.

**Comment by arthurdm** [comment]
hi @cthigh - You can build this on a mac too - that's what I am doing.  You still pick the linux IM link because it's Ubuntu inside the container.

**Comment by patricktiu** [comment]
It is the status from wget.  Maybe add "-q" option can suppress the status.

**Comment by arturdzm** [comment]
Looks to be resolved, closing
